package com.cyberintech.vrisk.server.model.jpa.domains;

public enum DataSpecificExemptionsType {
	NONE, PROTECTED_HEALTH_INFORMATION, INFORMATION_MAINTAINED_BY_HIPAA, PERSONAL_INFORMATION_COVERED_BY_ACTS, PERSONAL_DATA_OF_PERSONAL_OR_HOUSEHOLD, EMERGENCY_CONTACT_INFORMATION
}
