package com.cyberintech.vrisk.server.model.jpa.domains;

public enum EntryLevelExemptionsType {
	NONE, NONPROFIT, GOVERNMENT_ENTITIES, HIGHER_EDUCATIONAL_INSTITUTIONS, ELECTRIC_UTILITIES, FINANCIAL_INSTITUTIONS_GRAMM_LEACH_BLILEY_ACT, INSURANCE_COMPANIES, FCRA, DPPA, FERPA, FCA, ADA, HITECH, HIPPA_COVERED_ENTITIES, HIPAA_BUSINESS_ASSOCIATES, GRAMM_LEACH_BLILEY_ACT,SMALL_BUISNESS
}
