# Build properties
build.version=@project.version@
build.artifactId=@project.artifactId@

# Preferred JSON mapper to use for HTTP message conversion
spring.mvc.converters.preferred-json-mapper=jsonb

# Spring Cache config
# spring.cache.jcache.config=classpath:ehcache.xml

# Liquibase
# Change log configuration path.
spring.liquibase.change-log=classpath:liquibase/postgres/master-changelog.xml

# Spring MVC
spring.mvc.throw-exception-if-no-handler-found=true

# Liquibase
# Enable liquibase support.
# liquibase.enabled=true
# liquibase.drop-first=false

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
spring.servlet.multipart.max-file-size=200MB
# Max Request Size
spring.servlet.multipart.max-request-size=215MB

#Spring Boot Actuator Settings
info.app.name=RIskQ API
info.app.description=RiskQ REST API application
info.app.signature=20240929
info.app.releaseDate=2024-09-29
info.app.version=2.2.40

# endpoints.beans.id=springbeans
# endpoints.beans.sensitive=false
# endpoints.beans.enabled=true

# Core application Info
application.oauth.client.id=com.vrisk
application.oauth.client.signature=21827392bacff

# Logging
hibernate.generate_statistics=false
spring.session.store-type=none

#big id integration. test environment.
integration.bigid.client.authorization-username=bigid
integration.bigid.client.authorization-password=learner
integration.bigid.client.base-service-url=https://0-381.mybigid.com

# do not start Spring Batch job execution automatically after app is started
spring.batch.job.enabled=false
