#Swagger json mapping URL
# springfox.documentation.swagger.v2.path=/swagger/v2/api-docs

# Springdoc and Swagger UI config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.doc-expansion=none
