# Build properties
build.version=${project.version}
build.artifactId=${project.artifactId}

# Flyway
spring.flyway.baselineOnMigrate=true

# Spring
spring.mvc.throw-exception-if-no-handler-found=true
